name: cutesy
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  ffigen: ^6.0.0
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  bidi: ^2.0.6
  ffi: ^1.2.1
  glfw: ^0.5.0
  logging: ^1.1.0
  meta: ^1.9.0
  opengl: ^0.6.0
  path: ^1.8.3
  vector_math: ^2.1.4

dependency_overrides:
  ffi: ^2.0.2
  ffigen: ^8.0.2
